# Generated by Django 5.0.9 on 2025-12-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PunchDataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('from_date', models.CharField(max_length=50)),
                ('to_date', models.CharField(max_length=50)),
                ('punch_data', models.JSONField(default=list, help_text='Stored punch data as JSON')),
                ('total_records', models.IntegerField(default=0)),
                ('unique_employees', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('columns', models.JSONField(default=list, help_text='Column names in the CSV')),
                ('operations_summary', models.JSONField(blank=True, default=dict, help_text='Summary of operations performed', null=True)),
            ],
            options={
                'verbose_name': 'Punch Data File',
                'verbose_name_plural': 'Punch Data Files',
                'db_table': 'punch_data_files',
                'ordering': ['-created_at'],
            },
        ),
    ]
