# Generated by Django 6.0.4 on 2026-04-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empcode', models.CharField(db_index=True, max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'employee_details',
                'ordering': ['empcode'],
            },
        ),
        migrations.CreateModel(
            name='PunchDataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(blank=True, help_text='Blob storage URL or local file path', max_length=500, null=True)),
                ('blob_url', models.URLField(blank=True, help_text='Azure Blob Storage URL', max_length=1000, null=True)),
                ('blob_name', models.CharField(blank=True, help_text='Blob name in storage', max_length=255, null=True)),
                ('container_name', models.CharField(blank=True, help_text='Container name in blob storage', max_length=255, null=True)),
                ('from_date', models.CharField(max_length=50)),
                ('to_date', models.CharField(max_length=50)),
                ('total_records', models.IntegerField(default=0)),
                ('unique_employees', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Punch Data File',
                'verbose_name_plural': 'Punch Data Files',
                'db_table': 'punch_data_files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='all_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empcode', models.CharField(max_length=10)),
                ('in_time', models.CharField(max_length=10)),
                ('out_time', models.CharField(max_length=10)),
                ('work_time', models.CharField(max_length=10)),
                ('over_time', models.CharField(max_length=10)),
                ('break_time', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('date_string', models.DateField()),
                ('remark', models.CharField(max_length=100)),
                ('erl_out', models.CharField(max_length=10)),
                ('late_in', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'punch_data_all',
                'unique_together': {('empcode', 'date_string')},
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empcode', models.CharField(db_index=True, max_length=10)),
                ('email_type', models.CharField(max_length=50)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(db_index=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'db_table': 'email_log',
                'ordering': ['-sent_at'],
                'unique_together': {('empcode', 'email_type', 'date')},
            },
        ),
        migrations.CreateModel(
            name='mcid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('empcode', models.CharField(max_length=10)),
                ('punch_date', models.CharField(max_length=20)),
                ('punch_time', models.CharField(max_length=20)),
                ('m_flag', models.CharField(blank=True, max_length=2, null=True)),
                ('mcid', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'MCID Data',
                'verbose_name_plural': 'MCID Data',
                'db_table': 'punch_data_mcid',
                'unique_together': {('empcode', 'punch_date', 'punch_time', 'mcid')},
            },
        ),
        migrations.CreateModel(
            name='operational_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empcode', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('in_time', models.CharField(blank=True, max_length=20, null=True)),
                ('out_time', models.CharField(blank=True, max_length=20, null=True)),
                ('total_time', models.CharField(blank=True, max_length=10, null=True)),
                ('break_time', models.CharField(blank=True, max_length=10, null=True)),
                ('work_time', models.CharField(blank=True, max_length=10, null=True)),
                ('total_punches_count', models.IntegerField(blank=True, null=True)),
                ('invalid_punches_count', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'punch_data_operational',
                'unique_together': {('empcode', 'date')},
            },
        ),
    ]
