# Generated by Django 5.0.9 on 2025-12-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='punchdatafile',
            name='blob_name',
            field=models.CharField(blank=True, help_text='Blob name in storage', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='punchdatafile',
            name='blob_url',
            field=models.URLField(blank=True, help_text='Azure Blob Storage URL', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='punchdatafile',
            name='container_name',
            field=models.CharField(blank=True, help_text='Container name in blob storage', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='punchdatafile',
            name='file_path',
            field=models.CharField(blank=True, help_text='Blob storage URL or local file path', max_length=500, null=True),
        ),
    ]
