# Generated by Django 5.0.9 on 2025-12-30 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dj_app', '0002_punchdatafile_blob_name_punchdatafile_blob_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='punchdatafile',
            name='columns',
        ),
        migrations.RemoveField(
            model_name='punchdatafile',
            name='operations_summary',
        ),
        migrations.RemoveField(
            model_name='punchdatafile',
            name='punch_data',
        ),
    ]
