# Generated by Django 6.0 on 2026-01-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_app', '0003_remove_punchdatafile_columns_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='operational_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empcode', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('total_time', models.CharField(blank=True, max_length=10, null=True)),
                ('break_time', models.CharField(blank=True, max_length=10, null=True)),
                ('work_time', models.CharField(blank=True, max_length=10, null=True)),
                ('total_punches_count', models.IntegerField(blank=True, null=True)),
                ('invalid_punches_count', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
