# Generated by Django 5.0.9 on 2026-01-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_app', '0004_operational_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='operational_data',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operational_data',
            name='in_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='operational_data',
            name='out_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='operational_data',
            unique_together={('empcode', 'date')},
        ),
    ]
