# Generated by Django 6.0 on 2026-01-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_app', '0005_add_in_time_out_time_date_to_operational_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='all_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empcode', models.CharField(max_length=10)),
                ('in_time', models.CharField(max_length=10)),
                ('out_time', models.CharField(max_length=10)),
                ('work_time', models.CharField(max_length=10)),
                ('over_time', models.CharField(max_length=10)),
                ('break_time', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('date_string', models.DateField()),
                ('remark', models.CharField(max_length=100)),
                ('erl_out', models.CharField(max_length=10)),
                ('late_in', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('empcode',)},
            },
        ),
    ]
