# Generated by Django 5.0.9 on 2026-01-06 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dj_app', '0006_all_data'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='all_data',
            unique_together={('empcode', 'date_string')},
        ),
    ]
