# Generated by Django 6.0 on 2026-01-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_app', '0007_update_all_data_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='mcid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('empcode', models.CharField(max_length=10)),
                ('punch_date', models.CharField(max_length=20)),
                ('punch_time', models.CharField(max_length=20)),
                ('m_flag', models.CharField(blank=True, max_length=2, null=True)),
                ('mcid', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'MCID Data',
                'verbose_name_plural': 'MCID Data',
                'unique_together': {('empcode', 'punch_date', 'punch_time', 'mcid')},
            },
        ),
    ]
