# Generated by Django 6.0 on 2026-01-09 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dj_app', '0008_mcid'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='all_data',
            table='punch_data_all',
        ),
        migrations.AlterModelTable(
            name='mcid',
            table='punch_data_mcid',
        ),
        migrations.AlterModelTable(
            name='operational_data',
            table='punch_data_operational',
        ),
    ]
