# Generated by Django 6.0 on 2026-01-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_app', '0010_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empcode', models.CharField(db_index=True, max_length=10)),
                ('email_type', models.CharField(max_length=50)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(db_index=True)),
                ('details', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'db_table': 'email_log',
                'ordering': ['-sent_at'],
                'unique_together': {('empcode', 'email_type', 'date')},
            },
        ),
    ]

