# Generated by Django 5.2.10 on 2026-01-20 07:45

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dj_app', '0011_email_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_data',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='all_data',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
