# Generated by Django 5.2.10 on 2026-01-23 05:49

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dj_app', '0012_all_data_created_at_all_data_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emaillog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='operational_data',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operational_data',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
