"""
Django settings for dj_project project.

Generated by 'django-admin startproject' using Django 5.0.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import environ
import os
import dj_database_url

# django.db.backends.sqlite3
# django.db.backends.postgresql
# django.db.backends.mysql
# django.db.backends.oracle

# Load environment variables from .env file
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'django_apscheduler',
    'dj_app.apps.DjAppConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Add WhiteNoise for static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware'
    
]

ROOT_URLCONF = 'dj_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dj_project.wsgi.app'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# SQL Server Database configuration using environment variables from .env
# For remote SQL Server database (created on another system via SSMS):
# Required .env variables:
# DB_NAME - Database name (as shown in SSMS)
# DB_USER - SQL Server username (SQL Server Authentication)
# DB_PASSWORD - SQL Server password
# DB_HOST - Remote server IP address or hostname (e.g., 192.168.1.100 or server-name)
# DB_PORT - SQL Server port (default: 1433)
# Optional .env variables:
# DB_ENGINE - Database engine (default: mssql)
# DB_DRIVER - ODBC Driver name (default: ODBC Driver 17 for SQL Server)
# DB_INSTANCE - SQL Server instance name (optional, e.g., SQLEXPRESS)
DATABASES = {
    'default': {
        'ENGINE': env('DB_ENGINE', default='mssql'),
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST', default='localhost'),
        'PORT': env('DB_PORT', default='1433'),
        'OPTIONS': {
            # 'driver': env('DB_DRIVER', default='ODBC Driver 17 for SQL Server'),
            # 'extra_params': env('DB_EXTRA_PARAMS', default=''),
        },
        'CONN_MAX_AGE': 600,
    }
}

# DATABASES = {
#     'default': dj_database_url.config(
#         default=os.getenv('DATABASE_URL')
#     )
# }



# SQL Server Database Configuration
# Using mssql-django (Microsoft's official Django backend for SQL Server)
# For django-mssql-backend, use ENGINE: 'mssql'
# For mssql-django, use ENGINE: 'mssql'
# DATABASES = {
#     'default': {
#         'ENGINE': 'mssql',
#         'NAME': env('DB_NAME', default='db_attendence'),
#         'USER': env('DB_USER', default='praveen'),
#         'PASSWORD': env('DB_PASSWORD', default='Strong@Password123'),
#         'HOST': env('DB_HOST', default='192.168.144.1'),
#         'PORT': env('DB_PORT', default='1433'),
#         'OPTIONS': {
#             'driver': env('DB_DRIVER', default='ODBC Driver 17 for SQL Server'),
#             'extra_params': 'TrustServerCertificate=yes;',
#         },
#         'CONN_MAX_AGE': 600,
#     }
# }


# DATABASES = {
#     'default': {
#         'ENGINE': 'mssql',
#         'NAME':'db_attendence',
#         'USER': 'praveen',
#         'PASSWORD':'Strong@Password123',
#         'HOST':'192.168.0.160',
#         'PORT':'1433',
#         'OPTIONS': {
#             'driver': env('DB_DRIVER', default='ODBC Driver 17 for SQL Server'),
#             'extra_params': 'TrustServerCertificate=yes;',
#         },
#         'CONN_MAX_AGE': 600,
#     }
# }


# DATABASES = {
#     'default': {
#         'ENGINE': 'mssql',
#         'NAME': 'db_attendence',
#         'HOST': '192.168.0.160',
#         'OPTIONS': {
#             'driver': 'ODBC Driver 18 for SQL Server',
#             'trusted_connection': 'yes',
#             'TrustServerCertificate': 'yes',
#         },
#     }
# }



# If using named instance, construct connection string properly
# For named instances, HOST should be: server-name\instance-name or IP\instance-name


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'  # IST timezone

SECRET_KEY = env('DJANGO_SECRET_KEY')
USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'

# Directory where collectstatic will collect all static files for production
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS Configuration (for frontend API access)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:3001",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:3001",
    "https://fe-attendance-five.vercel.app",
]

# For development, allow all origins (remove in production)
CORS_ALLOW_ALL_ORIGINS = True  # Set to False in production and use CORS_ALLOWED_ORIGINS

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# APScheduler configuration
APSCHEDULER_DATETIME_FORMAT = "N j, Y, f:s a"
APSCHEDULER_RUN_NOW_TIMEOUT = 25  # Seconds

# Email Configuration
EMAIL_BACKEND = env('EMAIL_BACKEND')
EMAIL_HOST = env('EMAIL_HOST')
EMAIL_PORT = env('EMAIL_PORT')
EMAIL_USE_TLS = env('EMAIL_USE_TLS')
EMAIL_HOST_USER = env('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='no@reply.com')